### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by iamdey** [Gandi/react-translate#5]
Moment and other dependencies are declared as peerdepency but nor in normal dependencies: 

```
Module not found: Error: Cannot resolve module 'moment' in .../node_modules/@gandi/react-translate/dist/tools
resolve module moment in .../node_modules/@gandi/react-translate/dist/tools
...
@ ./~/@gandi/react-translate/dist/tools/createTranslator.js 15:14-31
```

**Comment by iamdey** [comment]
other dependencies in dev to check:

* colors
* lodash
* react
* react-dom

still used ?

* cheerio
* react-addons-test-utils

**Comment by pascalduez** [comment]
`colors, lodash`: used by the cli
`react, react-dom, react-addons-test-utils`: needed for the unit tests
`cheerio`: peerDependency of enzyme

As a rule of thumb, deps declared as peerDeps needs to be declared as devDeps for the unit tests.

**Comment by iamdey** [comment]
Thanks

Here are my guesses, what do you think ?

* colors, lodash: used by the cli **-> must be declared as normal deps**
* react, react-dom **-> used by components and tools, -> must be declared as normal deps**
* react-addons-test-utils: needed for the unit tests **-> I didn't find any requires**
* cheerio: peerDependency of enzyme **-> [declared as normal dep in enzyme](https://github.com/airbnb/enzyme/blob/master/package.json#L55), so it sounds useless here**

**Comment by pascalduez** [comment]
`colors`: agree, its should be a `dependency` it's really specific to this package.

`react, react-dom`: It was done that way to prevent having several versions of React in Apps.

`lodash`: same as above, but less problematic IMO.

`react-addons-test-utils`: try to run the tests without it, it should break. And it's a [peerDep](https://github.com/producthunt/chai-enzyme/blob/master/package.json#L32) of `chai-enzyme`.

`cheerio`: sorry, it's actually a [peerDep](https://github.com/producthunt/chai-enzyme/blob/master/package.json#L29) of `chai-enzyme`...

You'll need feedback from the frontend team on this topic I guess.

**Comment by yanndinendal** [comment]
@iamdey : Yes, a few of them are a recent regression (gandi.cli was put into peerDeps but missing in devDeps). Some are equivalent (having a peerDep to tell the app that consumes gandi.translate to install deps (and devDeps so they also work locally) works nearly the same as having them as real dependencies (it's just a matter of maintenance, where do you want to "force" the version number, etc). Generally, we use peerDeps to mutualize versions of some packages we use everywhere, but it makes more sense for internal packages.

So for @gandi/react-translate, we should avoid peerDeps. The only case where it makes sence is, as @pascalduez said, for react and react-dom, where we know the app that consumes react-translate **will** already have these deps, and we want to avoid having several versions of them in the final bundle.

**Comment by yanndinendal** [comment]
@iamdey @pascalduez 

So I would say:

* `colors`, `intl`, `lodash`, `moment` => `dependencies`
* `react`, `react-dom`: `peerDependencies` + `devDependencies`
* `lodash`: :question: Not sure... Could be a peerDep as react because it's really widely used... But I would say rather a `dependency` to be sure: that way, apps that don't use lodash don't have to maintain a version of lodash they don't use. And for those that do, they can always run `npm dedupe` if we ship a version of lodash different from them.
* no changes to tests devDeps

**Comment by pascalduez** [comment]
ping @Gandi/front

**Comment by ziir** [comment]
Let's get rid of lodash altogether :)

**Comment by ziir** [comment]
Can you edit the issue's title and summary so it's clearer which issue we're actually dealing with?
