### ISSUE TITLE
"Unknown props" warning

### ISSUE THREAD

**Issue by iamdey** [Gandi/react-translate#7]
When using `withTranslator` on a component I got this warning because it "pollutes" props with useless methods, for example:

```js
@withTranslator()
class Presenter extends React.PureComponent {
  render() {
    const { __, ...props } = this.props;

    return <Button {...props}>{__('foobar')}</Button>;
  }
}
```

Then:

```
bundle.js:2009 Warning: Unknown props `formatDate`, `formatNumber`, `formatPrice`, `formatCurrency`, `localize` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

I may delete unused helpers in each Component that will use translator ...or I don't.

---

What's the best way to fix that ?

1. Add a tool that looks like `mapDispatchToProps` instead of `withTranslator` 
2. Add a basic translator Component with enhancedTranslator only
3. ... ?

**Comment by pascalduez** [comment]
One solution we often use is namespacing:

```js
@withTranslator({ propsNamespace: 'translator' })
class Presenter extends React.PureComponent {
  render() {
    const { translator: { __ }, ...props } = this.props;

    return <Button {...props}>{__('foobar')}</Button>;
  }
}
```

**Comment by iamdey** [comment]
Awesome. 

So the point 3. is "Improve README" :)
